### ISSUE TITLE
No results after search : username, repository title, addon id

### ISSUE THREAD

**Issue by karlo2105** [azzy9/plugin.git.browser#1]
When i make search by github username, repository title, addon id, i don't get any results. I tried with several projects. Could you give me a tip how to get results from gitbrowser ?
Thanks ;-)

**Comment by azzy9** [comment]
Hi, thank you for your interest in this project.
It ins't fully functional yet as I need to apply changes to API to get it working.
I am assuming it is only pushing the API key into the header but still need to look into it.

**Comment by azzy9** [comment]
This is fixed in v2.0.0
